name: build
on:
  push:
    branches:
      - main
      - issue1
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Build MikanOS
        run: make build
      - name: Upload MikanOS
        uses: actions/upload-artifact@main
        with:
          name: MikanOS
          path: disk

