name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Make shell scripts executable
        run: chmod u+x *.sh
      - name: Build MikanOS
        run: make image
      - name: Upload MikanOS
        uses: actions/upload-artifact@main
        with:
          name: MikanOS
          path: disk.img

